name: LASYLAB
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  custom_line_indicator_bottom_navbar: ^0.0.7
  custom_pop_up_menu: ^1.2.2
  device_preview: ^1.1.0
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  flutter_shimmer: ^2.1.2
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.6.0
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.0+2
  logger:
  lottie: ^2.7.0
  path_provider: ^2.0.8
  pausable_timer: ^3.1.0+3
  pin_code_fields: ^8.0.1
  pinput: ^3.0.1
  provider: ^6.0.3
  record: ^5.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  transparent_image: ^2.0.0
  permission_handler:
  video_player: ^2.8.1
  chewie: ^1.7.1
  audioplayers: ^5.2.0
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  #image: assets/images/splash.png
  image: assets/images/logo-lasylab.png
  android: true
  ios: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/IconeApp.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
    - assets/json/
    - assets/audio/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
